"""
TopperGPT - Legal & Compliance Module
Comprehensive Privacy Policy, Terms & Conditions, and Cookie Policy for TopperGPT.
Provides Markdown and HTML formats for in-app dialogs, standalone pages, and landing page modal.
"""

try:
    import streamlit as st
except ImportError:
    st = None

TERMS_OF_SERVICE_MD = """
# Terms of Service & Academic Use Agreement
*Last Updated: October 2026*

Welcome to **TopperGPT** (accessible via [https://toppergpt.in](https://toppergpt.in)). By accessing, registering for, or using our AI Academic Workspace, you agree to be bound by these Terms of Service. If you do not agree, please discontinue using the platform immediately.

---

### 1. Platform Purpose & Scope of Service
TopperGPT is an advanced artificial intelligence academic workspace engineered to assist engineering students (with specialized alignment to Mumbai University C-Scheme curricula) in understanding technical concepts, revising syllabi, solving academic doubts, and practicing examination-style questions.

### 2. Academic Integrity & Responsible Use Policy
TopperGPT is strictly an **educational comprehension and study assistance tool**.
- **Prohibited Conduct:** You agree **NEVER** to use TopperGPT for real-time unauthorized cheating during live in-person or proctored university examinations, practical viva evaluations, or tests where external assistance is prohibited.
- **Fair Academic Learning:** Content generated by TopperGPT (step-by-step derivations, solved problems, and revision notes) is intended to help you learn, master problem-solving methodologies, and verify your self-study practice.

### 3. AI-Generated Output & Academic Verification Disclaimer
- TopperGPT utilizes state-of-the-art Large Language Models (LLMs) including Google Gemini and Groq Llama architectures to synthesize academic solutions.
- While our systems are rigorously tuned and evaluated against university syllabus standards, **AI-generated responses may occasionally contain inadvertent approximations, non-standard notations, or arithmetic anomalies**.
- Students are strongly advised to cross-reference final formulas, university marking schemes, and numerical constants with their prescribed university textbooks and syllabus guidelines.
- TopperGPT Inc. does not guarantee specific examination scores or grades.

### 4. User Accounts & Security
- To access personalized study features (chat history, syllabus tracking, predicted questions), you must authenticate with a valid email address.
- You are solely responsible for maintaining the confidentiality of your credentials and all activities occurring under your account.
- You agree not to share your account or attempt unauthorized penetration testing, scraping, or denial-of-service attacks against TopperGPT infrastructure.

### 5. Intellectual Property
- The TopperGPT name, brand assets, logos, user interface designs, custom prompt templates, and software code are the exclusive intellectual property of TopperGPT Inc.
- Course syllabi, question papers, and textbook references belong to their respective university copyright holders and are referenced under educational fair-use principles.

### 6. Service Availability & Modifications
We strive for 99.9% platform availability. However, service may be occasionally interrupted for system upgrades, container scaling, or API maintenance. We reserve the right to modify, suspend, or discontinue any feature with or without notice.

### 7. Limitation of Liability
To the maximum extent permitted by applicable law, TopperGPT Inc. and its operators shall not be liable for any indirect, incidental, punitive, or consequential damages arising from your use of or inability to use the platform.

### 8. Governing Law & Jurisdiction
These Terms shall be governed by and construed in accordance with the laws of the Republic of India. Any disputes arising hereunder shall be subject to the exclusive jurisdiction of the competent courts in Mumbai, Maharashtra, India.

### 9. Contact Us
For legal inquiries, copyright notices, or terms clarification, please contact our legal team at:
- **Email:** `support@toppergpt.in` or `legal@toppergpt.in`
- **Feedback Portal:** Accessible directly inside the TopperGPT application menu.
"""

PRIVACY_POLICY_MD = """
# Privacy Policy & Data Protection
*Last Updated: October 2026*

At **TopperGPT** ("we", "our", or "us"), we are deeply committed to safeguarding the privacy and personal data of our student community. This Privacy Policy outlines what information we collect, how it is processed, and your rights regarding your data.

---

### 1. Information We Collect
We collect only the minimum information necessary to provide an exceptional, tailored academic learning experience:
- **Account Details:** Your email address, full name, and academic preferences (university, branch, semester) provided during registration or profile setup.
- **Academic Queries & Chat Interactions:** Questions asked to the AI Tutor, selected subjects, and revision notes to enable continuous multi-turn chat sessions and historical study review.
- **Uploaded Academic Documents & Images:** Question papers, syllabus PDFs, or circuit diagrams you choose to upload for explanation. Document text and base64 image data are processed in-memory for solution generation and purged from runtime memory once the answer is synthesized.
- **Feedback Submissions:** Category, rating, and suggestions submitted via our feedback form, stored securely in our Supabase database.
- **Technical & Device Telemetry:** Standard web server logs, IP address (hashed/anonymized), browser user-agent, and cookie identifiers for authentication.

### 2. How We Use Your Information
- **Delivering Academic Solutions:** Routing your syllabus questions to our AI inference pipeline to generate derivations, answers, and study notes.
- **Session Continuity:** Synchronizing your chat history across your desktop and mobile devices via encrypted Supabase database tables.
- **Product Improvement:** Identifying common subject bottlenecks to improve question predictions and syllabus coverage.
- **Zero Commercial Sale:** We **NEVER sell, rent, or monetize your personal data** to third-party data brokers or advertisers.

### 3. Data Protection & Security Architecture
- **Encryption in Transit:** All traffic between your browser and TopperGPT servers is strictly encrypted using TLS 1.3 (HTTPS).
- **Row Level Security (RLS):** Database storage in Supabase enforces strict user-level Row Level Security policies—students can only access and view their own private study records.
- **Ephemeral File Processing:** Uploaded PDFs and images are processed ephemerally. Heavy image payloads are pruned from database storage to safeguard privacy.

### 4. Third-Party AI Processors
- To generate accurate academic solutions, anonymized academic query prompts are transmitted to enterprise AI API endpoints (Google Gemini API, Groq Cloud, OpenRouter).
- Our enterprise API agreements mandate that student queries are **NOT utilized to train public foundation models**.

### 5. Cookies & Local Storage
We use strictly necessary session cookies and browser `localStorage` to:
- Maintain your authenticated session.
- Store your dark-mode UI preference.
- Record your cookie consent preference.
For more details, please review our [Cookie Policy](#cookie-policy).

### 6. Your Data Rights & Deletion
Under applicable data privacy regulations, you have the right to:
- **Access Your Data:** View your profile details and saved study history at any time.
- **Delete Your History:** Click **"Clear Chat"** inside the AI Tutor to instantly wipe your active conversation records from both local cache and database storage.
- **Account Erasure:** Request full account and data deletion by emailing `privacy@toppergpt.in`.

### 7. Changes to this Policy
We may periodically update this Privacy Policy to reflect technical enhancements or regulatory changes. We will notify users of material modifications by updating the "Last Updated" date.

### 8. Contact Our Privacy Team
If you have questions, concerns, or requests regarding your personal data:
- **Email:** `privacy@toppergpt.in` or `support@toppergpt.in`
"""

COOKIE_POLICY_MD = """
# Cookie & Storage Policy
*Last Updated: October 2026*

This Cookie Policy explains how **TopperGPT** utilizes cookies, browser `localStorage`, and related technologies to provide a fast, secure, and personalized study workspace.

---

### 1. What Are Cookies?
Cookies are small text files stored on your device by your web browser when visiting websites. Local storage (`localStorage`) allows web applications to store data client-side for performance and persistent preferences.

### 2. Categories of Cookies We Use
TopperGPT utilizes only essential and functional storage mechanisms:

| Category | Storage Key / Name | Purpose | Duration |
| :--- | :--- | :--- | :--- |
| **Strictly Necessary** | `sb-access-token` / Session | Authenticates your student session and secures database queries. | Session / 30 Days |
| **Strictly Necessary** | `toppergpt_cookie_consent` | Remembers whether you have acknowledged our Cookie Consent Banner. | 1 Year (`localStorage`) |
| **Functional** | `theme_choice` | Preserves your preferred UI theme (Permanent Cyber Dark). | Persistent |
| **Functional** | `sidebar_state` | Remembers whether your navigation sidebar is open or collapsed. | Session |
| **Performance** | `.user_chats` / Cache | Caches recent chat replies to eliminate duplicate API calls and reduce latency. | Rolling 30 Days |

### 3. Third-Party Cookies
TopperGPT **does NOT load third-party advertising cookies, behavioral tracking pixels (e.g. Facebook Pixel), or marketing trackers**. We keep our platform completely distraction-free and private for students.

### 4. How to Manage or Disable Cookies
- Most modern browsers allow you to view, manage, and block cookies through their security settings.
- Please note that disabling **Strictly Necessary Cookies** will prevent you from logging into your account and synchronizing your study history.
- To reset your local storage preferences on TopperGPT, you can clear site data for `toppergpt.in` in your browser settings.

### 5. Contact Us
For questions regarding our use of cookies and local storage:
- **Email:** `support@toppergpt.in`
"""

# Pre-rendered Clean Semantic HTML for direct embed in landing page modal
TERMS_OF_SERVICE_HTML = """
<div style="font-family: 'Space Grotesk', -apple-system, sans-serif; color: #cbd5e1; line-height: 1.65;">
  <h2 style="color: #58c1c8; font-size: 22px; font-weight: 800; margin: 0 0 4px 0;">Terms of Service & Academic Use Agreement</h2>
  <div style="color: #94a3b8; font-size: 12.5px; margin-bottom: 18px;"><em>Last Updated: October 2026</em></div>
  <p style="margin-bottom: 16px;">Welcome to <strong>TopperGPT</strong> (accessible via <a href="https://toppergpt.in" target="_blank" style="color: #58c1c8; text-decoration: underline;">https://toppergpt.in</a>). By accessing, registering for, or using our AI Academic Workspace, you agree to be bound by these Terms of Service. If you do not agree, please discontinue using the platform immediately.</p>
  
  <hr style="border: none; border-top: 1px solid rgba(255, 255, 255, 0.08); margin: 20px 0;" />

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">1. Platform Purpose & Scope of Service</h3>
  <p style="margin-bottom: 14px;">TopperGPT is an advanced artificial intelligence academic workspace engineered to assist engineering students (with specialized alignment to Mumbai University C-Scheme curricula) in understanding technical concepts, revising syllabi, solving academic doubts, and practicing examination-style questions.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">2. Academic Integrity & Responsible Use Policy</h3>
  <p style="margin-bottom: 8px;">TopperGPT is strictly an <strong>educational comprehension and study assistance tool</strong>.</p>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;"><strong style="color: #f87171;">Prohibited Conduct:</strong> You agree <strong>NEVER</strong> to use TopperGPT for real-time unauthorized cheating during live in-person or proctored university examinations, practical viva evaluations, or tests where external assistance is prohibited.</li>
    <li style="margin-bottom: 6px;"><strong>Fair Academic Learning:</strong> Content generated by TopperGPT (step-by-step derivations, solved problems, and revision notes) is intended to help you learn, master problem-solving methodologies, and verify your self-study practice.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">3. AI-Generated Output & Academic Verification Disclaimer</h3>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;">TopperGPT utilizes state-of-the-art Large Language Models (LLMs) including Google Gemini and Groq Llama architectures to synthesize academic solutions.</li>
    <li style="margin-bottom: 6px;">While our systems are rigorously tuned and evaluated against university syllabus standards, <strong>AI-generated responses may occasionally contain inadvertent approximations, non-standard notations, or arithmetic anomalies</strong>.</li>
    <li style="margin-bottom: 6px;">Students are strongly advised to cross-reference final formulas, university marking schemes, and numerical constants with their prescribed university textbooks and syllabus guidelines.</li>
    <li style="margin-bottom: 6px;">TopperGPT Inc. does not guarantee specific examination scores or grades.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">4. User Accounts & Security</h3>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;">To access personalized study features (chat history, syllabus tracking, predicted questions), you must authenticate with a valid email address.</li>
    <li style="margin-bottom: 6px;">You are solely responsible for maintaining the confidentiality of your credentials and all activities occurring under your account.</li>
    <li style="margin-bottom: 6px;">You agree not to share your account or attempt unauthorized penetration testing, scraping, or denial-of-service attacks against TopperGPT infrastructure.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">5. Intellectual Property</h3>
  <p style="margin-bottom: 14px;">The TopperGPT name, brand assets, logos, user interface designs, custom prompt templates, and software code are the exclusive intellectual property of TopperGPT Inc. Course syllabi, question papers, and textbook references belong to their respective university copyright holders and are referenced under educational fair-use principles.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">6. Service Availability & Modifications</h3>
  <p style="margin-bottom: 14px;">We strive for 99.9% platform availability. However, service may be occasionally interrupted for system upgrades, container scaling, or API maintenance. We reserve the right to modify, suspend, or discontinue any feature with or without notice.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">7. Limitation of Liability</h3>
  <p style="margin-bottom: 14px;">To the maximum extent permitted by applicable law, TopperGPT Inc. and its operators shall not be liable for any indirect, incidental, punitive, or consequential damages arising from your use of or inability to use the platform.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">8. Governing Law & Jurisdiction</h3>
  <p style="margin-bottom: 14px;">These Terms shall be governed by and construed in accordance with the laws of the Republic of India. Any disputes arising hereunder shall be subject to the exclusive jurisdiction of the competent courts in Mumbai, Maharashtra, India.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">9. Contact Us</h3>
  <p style="margin-bottom: 14px;">For legal inquiries, copyright notices, or terms clarification, please contact our legal team at:<br>
  • <strong>Email:</strong> <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">support@toppergpt.in</code> or <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">legal@toppergpt.in</code></p>
</div>
"""

PRIVACY_POLICY_HTML = """
<div style="font-family: 'Space Grotesk', -apple-system, sans-serif; color: #cbd5e1; line-height: 1.65;">
  <h2 style="color: #58c1c8; font-size: 22px; font-weight: 800; margin: 0 0 4px 0;">Privacy Policy & Data Protection</h2>
  <div style="color: #94a3b8; font-size: 12.5px; margin-bottom: 18px;"><em>Last Updated: October 2026</em></div>
  <p style="margin-bottom: 16px;">At <strong>TopperGPT</strong> ("we", "our", or "us"), we are deeply committed to safeguarding the privacy and personal data of our student community. This Privacy Policy outlines what information we collect, how it is processed, and your rights regarding your data.</p>
  
  <hr style="border: none; border-top: 1px solid rgba(255, 255, 255, 0.08); margin: 20px 0;" />

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">1. Information We Collect</h3>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;"><strong>Account Details:</strong> Your email address, full name, and academic preferences (university, branch, semester) provided during registration or profile setup.</li>
    <li style="margin-bottom: 6px;"><strong>Academic Queries & Chat Interactions:</strong> Questions asked to the AI Tutor, selected subjects, and revision notes to enable continuous multi-turn chat sessions and historical study review.</li>
    <li style="margin-bottom: 6px;"><strong>Uploaded Academic Documents & Images:</strong> Question papers, syllabus PDFs, or circuit diagrams you choose to upload for explanation. Processed in-memory for solution generation and purged from runtime memory once synthesized.</li>
    <li style="margin-bottom: 6px;"><strong>Feedback Submissions:</strong> Category, rating, and suggestions submitted via our feedback form, stored securely in our Supabase database.</li>
    <li style="margin-bottom: 6px;"><strong>Technical & Device Telemetry:</strong> Standard web server logs, IP address (hashed/anonymized), browser user-agent, and cookie identifiers for authentication.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">2. How We Use Your Information</h3>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;"><strong>Delivering Academic Solutions:</strong> Routing your syllabus questions to our AI inference pipeline to generate derivations, answers, and study notes.</li>
    <li style="margin-bottom: 6px;"><strong>Session Continuity:</strong> Synchronizing your chat history across your desktop and mobile devices via encrypted Supabase database tables.</li>
    <li style="margin-bottom: 6px;"><strong>Product Improvement:</strong> Identifying common subject bottlenecks to improve question predictions and syllabus coverage.</li>
    <li style="margin-bottom: 6px;"><strong style="color: #4ade80;">Zero Commercial Sale:</strong> We <strong>NEVER sell, rent, or monetize your personal data</strong> to third-party data brokers or advertisers.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">3. Data Protection & Security Architecture</h3>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;"><strong>Encryption in Transit:</strong> All traffic between your browser and TopperGPT servers is strictly encrypted using TLS 1.3 (HTTPS).</li>
    <li style="margin-bottom: 6px;"><strong>Row Level Security (RLS):</strong> Database storage in Supabase enforces strict user-level Row Level Security policies—students can only access and view their own private study records.</li>
    <li style="margin-bottom: 6px;"><strong>Ephemeral File Processing:</strong> Uploaded PDFs and images are processed ephemerally. Heavy image payloads are pruned from database storage to safeguard privacy.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">4. Third-Party AI Processors</h3>
  <p style="margin-bottom: 14px;">To generate accurate academic solutions, anonymized academic query prompts are transmitted to enterprise AI API endpoints (Google Gemini API, Groq Cloud, OpenRouter). Our enterprise API agreements mandate that student queries are <strong>NOT utilized to train public foundation models</strong>.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">5. Cookies & Local Storage</h3>
  <p style="margin-bottom: 14px;">We use strictly necessary session cookies and browser <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">localStorage</code> to maintain your authenticated session, store your dark-mode UI preference, and record your cookie consent choice.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">6. Your Data Rights & Deletion</h3>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;"><strong>Access Your Data:</strong> View your profile details and saved study history at any time.</li>
    <li style="margin-bottom: 6px;"><strong>Delete Your History:</strong> Click <strong>"Clear Chat"</strong> inside the AI Tutor to instantly wipe your active conversation records from both local cache and database storage.</li>
    <li style="margin-bottom: 6px;"><strong>Account Erasure:</strong> Request full account and data deletion by emailing <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">privacy@toppergpt.in</code>.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">7. Contact Our Privacy Team</h3>
  <p style="margin-bottom: 14px;">If you have questions, concerns, or requests regarding your personal data:<br>
  • <strong>Email:</strong> <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">privacy@toppergpt.in</code> or <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">support@toppergpt.in</code></p>
</div>
"""

COOKIE_POLICY_HTML = """
<div style="font-family: 'Space Grotesk', -apple-system, sans-serif; color: #cbd5e1; line-height: 1.65;">
  <h2 style="color: #58c1c8; font-size: 22px; font-weight: 800; margin: 0 0 4px 0;">Cookie & Storage Policy</h2>
  <div style="color: #94a3b8; font-size: 12.5px; margin-bottom: 18px;"><em>Last Updated: October 2026</em></div>
  <p style="margin-bottom: 16px;">This Cookie Policy explains how <strong>TopperGPT</strong> utilizes cookies, browser <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">localStorage</code>, and related technologies to provide a fast, secure, and personalized study workspace.</p>
  
  <hr style="border: none; border-top: 1px solid rgba(255, 255, 255, 0.08); margin: 20px 0;" />

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">1. What Are Cookies?</h3>
  <p style="margin-bottom: 14px;">Cookies are small text files stored on your device by your web browser when visiting websites. Local storage allows web applications to store data client-side for performance and persistent preferences.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">2. Categories of Storage We Use</h3>
  <div style="overflow-x: auto; margin-bottom: 18px;">
    <table style="width: 100%; border-collapse: collapse; font-size: 13px; text-align: left;">
      <thead>
        <tr style="border-bottom: 1.5px solid rgba(88, 193, 200, 0.4); background: rgba(88, 193, 200, 0.08);">
          <th style="padding: 10px 12px; color: #58c1c8;">Category</th>
          <th style="padding: 10px 12px; color: #58c1c8;">Storage Key</th>
          <th style="padding: 10px 12px; color: #58c1c8;">Purpose</th>
          <th style="padding: 10px 12px; color: #58c1c8;">Duration</th>
        </tr>
      </thead>
      <tbody>
        <tr style="border-bottom: 1px solid rgba(255, 255, 255, 0.06);">
          <td style="padding: 10px 12px; font-weight: 600; color: #ffffff;">Strictly Necessary</td>
          <td style="padding: 10px 12px; font-family: monospace; color: #94a3b8;">sb-access-token</td>
          <td style="padding: 10px 12px;">Authenticates student session and secures database queries.</td>
          <td style="padding: 10px 12px;">Session / 30 Days</td>
        </tr>
        <tr style="border-bottom: 1px solid rgba(255, 255, 255, 0.06);">
          <td style="padding: 10px 12px; font-weight: 600; color: #ffffff;">Strictly Necessary</td>
          <td style="padding: 10px 12px; font-family: monospace; color: #94a3b8;">toppergpt_cookie_consent</td>
          <td style="padding: 10px 12px;">Remembers that you acknowledged our Cookie Consent Banner.</td>
          <td style="padding: 10px 12px;">1 Year (localStorage)</td>
        </tr>
        <tr style="border-bottom: 1px solid rgba(255, 255, 255, 0.06);">
          <td style="padding: 10px 12px; font-weight: 600; color: #ffffff;">Functional</td>
          <td style="padding: 10px 12px; font-family: monospace; color: #94a3b8;">theme_choice</td>
          <td style="padding: 10px 12px;">Preserves your preferred UI theme (Permanent Cyber Dark).</td>
          <td style="padding: 10px 12px;">Persistent</td>
        </tr>
        <tr style="border-bottom: 1px solid rgba(255, 255, 255, 0.06);">
          <td style="padding: 10px 12px; font-weight: 600; color: #ffffff;">Functional</td>
          <td style="padding: 10px 12px; font-family: monospace; color: #94a3b8;">sidebar_state</td>
          <td style="padding: 10px 12px;">Remembers whether your navigation sidebar is open or collapsed.</td>
          <td style="padding: 10px 12px;">Session</td>
        </tr>
        <tr>
          <td style="padding: 10px 12px; font-weight: 600; color: #ffffff;">Performance</td>
          <td style="padding: 10px 12px; font-family: monospace; color: #94a3b8;">.user_chats</td>
          <td style="padding: 10px 12px;">Caches recent chat replies to eliminate duplicate API calls and reduce latency.</td>
          <td style="padding: 10px 12px;">Rolling 30 Days</td>
        </tr>
      </tbody>
    </table>
  </div>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">3. Third-Party Trackers</h3>
  <p style="margin-bottom: 14px;">TopperGPT <strong>does NOT load third-party advertising cookies, behavioral tracking pixels (e.g. Facebook Pixel), or marketing trackers</strong>. We keep our platform completely distraction-free and private for students.</p>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">4. How to Manage Cookies</h3>
  <ul style="padding-left: 20px; margin-bottom: 14px;">
    <li style="margin-bottom: 6px;">Most modern browsers allow you to view, manage, and block cookies through their security settings.</li>
    <li style="margin-bottom: 6px;">Please note that disabling <strong>Strictly Necessary Cookies</strong> will prevent you from logging into your account and synchronizing your study history.</li>
    <li style="margin-bottom: 6px;">To reset your local storage preferences on TopperGPT, you can clear site data for <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">toppergpt.in</code> in your browser settings.</li>
  </ul>

  <h3 style="color: #ffffff; font-size: 16px; margin: 18px 0 8px 0;">5. Contact Us</h3>
  <p style="margin-bottom: 14px;">For questions regarding our use of cookies and local storage:<br>
  • <strong>Email:</strong> <code style="background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; color: #58c1c8;">support@toppergpt.in</code></p>
</div>
"""

def get_terms_html() -> str:
    """Returns clean HTML string for Terms of Service."""
    return TERMS_OF_SERVICE_HTML

def get_privacy_html() -> str:
    """Returns clean HTML string for Privacy Policy."""
    return PRIVACY_POLICY_HTML

def get_cookies_html() -> str:
    """Returns clean HTML string for Cookie Policy."""
    return COOKIE_POLICY_HTML


def render_standalone_legal_page(initial_tab: str = "terms"):
    """
    Renders a standalone, fully-responsive, branded legal page for direct URLs:
    /?page=terms, /?page=privacy, or /?page=cookies.
    """
    if st is None:
        return

    clean_tab = str(initial_tab or "").lower().strip()

    # Clean navigation header with Back button
    st.markdown("""
        <style>
        button[key="legal_back_btn"],
        div:has(> button[key="legal_back_btn"]) button {
            background: rgba(255, 255, 255, 0.04) !important;
            border: 1px solid rgba(88, 193, 200, 0.3) !important;
            border-radius: 9999px !important;
            color: #58c1c8 !important;
            font-weight: 600 !important;
            font-size: 13px !important;
            padding: 7px 18px !important;
            transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1) !important;
        }
        button[key="legal_back_btn"]:hover,
        div:has(> button[key="legal_back_btn"]) button:hover {
            background: rgba(88, 193, 200, 0.12) !important;
            border-color: rgba(88, 193, 200, 0.6) !important;
            color: #ffffff !important;
            transform: translateX(-2px) !important;
        }
        </style>
    """, unsafe_allow_html=True)

    col_nav, col_space = st.columns([2, 5])
    with col_nav:
        if st.button("← Back to Workspace", key="legal_back_btn", use_container_width=True):
            st.query_params.clear()
            st.rerun()

    st.markdown("""
        <div style="background: linear-gradient(135deg, rgba(88, 193, 200, 0.12) 0%, rgba(11, 15, 25, 0.95) 100%);
                    border: 1.5px solid rgba(88, 193, 200, 0.35);
                    border-radius: 14px;
                    padding: 24px 28px;
                    margin: 16px 0 24px 0;">
            <div style="display:flex; align-items:center; gap:12px; margin-bottom:8px;">
                <span style="font-size:28px;">⚖️</span>
                <div>
                    <h2 style="color:#58c1c8; margin:0; font-size:24px; font-weight:800; letter-spacing:0.5px;">TopperGPT Legal, Compliance & Privacy Center</h2>
                    <p style="color:#94a3b8; font-size:13.5px; margin:4px 0 0 0;">Official regulatory documentation, terms of service, data protection, and cookie disclosures.</p>
                </div>
            </div>
        </div>
    """, unsafe_allow_html=True)

    # Dynamic tab ordering so requested initial_tab is displayed first
    if clean_tab in ("privacy", "privacy-policy"):
        tab_privacy, tab_terms, tab_cookies = st.tabs([
            "🔒 Privacy Policy",
            "📜 Terms of Service",
            "🍪 Cookie Policy"
        ])
    elif clean_tab in ("cookies", "cookie-policy"):
        tab_cookies, tab_terms, tab_privacy = st.tabs([
            "🍪 Cookie Policy",
            "📜 Terms of Service",
            "🔒 Privacy Policy"
        ])
    else:
        tab_terms, tab_privacy, tab_cookies = st.tabs([
            "📜 Terms of Service",
            "🔒 Privacy Policy",
            "🍪 Cookie Policy"
        ])

    with tab_terms:
        st.markdown(TERMS_OF_SERVICE_MD)

    with tab_privacy:
        st.markdown(PRIVACY_POLICY_MD)

    with tab_cookies:
        st.markdown(COOKIE_POLICY_MD)

    st.markdown("<div style='height: 40px;'></div>", unsafe_allow_html=True)
    st.markdown("""
        <div style="text-align: center; color: #64748b; font-size: 13px; border-top: 1px solid rgba(255,255,255,0.08); padding-top: 16px;">
            © 2024–2026 TopperGPT Inc. All rights reserved. • Mumbai, Maharashtra, India
        </div>
    """, unsafe_allow_html=True)


if st is not None:
    @st.dialog("📜 Legal & Privacy Policies", width="large")
    def show_legal_dialog(active_tab: str = "terms"):
        """Streamlit Dialog (Modal) for instant in-app legal review without leaving the active chat session."""
        clean_tab = str(active_tab or "").lower().strip()
        if clean_tab in ("privacy", "privacy-policy"):
            tab_p, tab_t, tab_c = st.tabs(["🔒 Privacy Policy", "📜 Terms of Service", "🍪 Cookie Policy"])
        elif clean_tab in ("cookies", "cookie-policy"):
            tab_c, tab_t, tab_p = st.tabs(["🍪 Cookie Policy", "📜 Terms of Service", "🔒 Privacy Policy"])
        else:
            tab_t, tab_p, tab_c = st.tabs(["📜 Terms of Service", "🔒 Privacy Policy", "🍪 Cookie Policy"])

        with tab_t:
            st.markdown(TERMS_OF_SERVICE_MD)
        with tab_p:
            st.markdown(PRIVACY_POLICY_MD)
        st.markdown("""
            <style>
            button[key="btn_close_legal_dialog"],
            div:has(> button[key="btn_close_legal_dialog"]) button {
                background: rgba(255, 255, 255, 0.05) !important;
                border: 1px solid rgba(255, 255, 255, 0.12) !important;
                border-radius: 9999px !important;
                color: #e2e8f0 !important;
                font-weight: 600 !important;
                font-size: 13px !important;
                padding: 7px 20px !important;
                transition: all 0.2s ease !important;
            }
            button[key="btn_close_legal_dialog"]:hover,
            div:has(> button[key="btn_close_legal_dialog"]) button:hover {
                background: rgba(255, 255, 255, 0.12) !important;
                border-color: rgba(255, 255, 255, 0.25) !important;
                color: #ffffff !important;
            }
            </style>
        """, unsafe_allow_html=True)
        if st.button("Close Window", key="btn_close_legal_dialog", use_container_width=True):
            st.rerun()
else:
    def show_legal_dialog(active_tab: str = "terms"):
        """Fallback when streamlit is not installed in current environment."""
        pass

